---
title: "Data_wrangling_2"
author: "Clement Mugenzi"
date: "10/10/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(httr)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


## Get some data


read in the NSDUH data
```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_xml = read_html(url)

drug_use_xml = read_html(url) 

# extracting a single table among the 15.
  
table_list = (drug_use_xml %>% html_nodes(css = "table")) 
tabl_marj =
  table_list[[1]] %>% 
  html_table() %>% 
  slice(-1) %>% 
  as_tibble()
tabl_marj
```



## Get harry potter data

```{r}
hpsaga_html = 
  read_html("https://www.imdb.com/list/ls000630791/")
```


```{r}
hp_movie_names = 
  hpsaga_html %>% 
  html_nodes(".lister-item-header a") %>% 
  html_text()


hp_movie_runtimes = 
  hpsaga_html %>% 
  html_nodes(".runtime") %>% 
  html_text()

hp_movie_money = 
  hpsaga_html %>% 
  html_nodes(".text-muted .ghost~ .text-muted+ span") %>% 
  html_text()

hp_df = 
  tibble(
    title = hp_movie_names,
    runtime = hp_movie_runtimes,
    money = hp_movie_money)

```



## Get napoleon

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```


## Using an API

```{r}
# GET is used for APIs
nyc_water_df = 
  GET("https://data.cityofnewyork.us/resource/waf7-5gvc.csv") %>% 
  content()
```

## Using JSON

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/waf7-5gvc.json") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```

## Using the brfss data

```{r}
brfss_smart2010 = 
  GET("https://catalog.data.gov/dataset/percent-of-adult-current-smokers-by-sex-and-race-ethnicity-1995-2010") %>% 
  content("parsed")
```

## Pokemon API

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()
poke$abilities
poke$name
```
















